"""Type stubs for the ithmb_core Rust extension (abi3)."""

from typing import Any

def decode_ithmb(data: bytes, canceled: Any | None = None) -> dict[str, Any]: ...
def open_ithmb(data: bytes, canceled: Any | None = None) -> list[dict[str, Any]]: ...
def list_profiles() -> list[dict[str, Any]]: ...
